{
 "title": "Core Routing Overview",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": "prod, int, internal-dev, ref, ref2, refmock, refmock2, staging, uat"
   },
   { "name": "datasrc", "label": "Datasource", "query": "cloudwatch" },
   {
    "name": "almDataSrc",
    "label": "Alarm Data Source",
    "query": "computest-cloudwatchalarm-datasource"
   },
   {
    "name": "enrichmentQueueName",
    "query": "comms-${env}-api-stl-enrich-queue"
   },
   {
    "name": "enrichmentDlqName",
    "query": "comms-${env}-api-stl-enrich-dlq"
   },
   {
    "name": "reEnrichmentQueueName",
    "query": "comms-${env}-api-stl-reenrich-queue"
   },
   {
    "name": "tllLogId",
    "query": {}
   },
   {
    "name": "reEnrichmentDlqName",
    "query": "comms-${env}-api-stl-reenrich-dlq"
   }
  ]
 },
 "panels": [
  {
   "title": "Composite Alarm Statuses",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "region": "eu-west-2" }
   ]
  },
  {
   "title": "Client Requests Queued",
   "type": "status-history",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "dimensions": { "Environment": "$env", "status": "PENDING" },
     "metricName": "virtual_queue_insertion",
     "namespace": "comms-process-queue-updates-lambda-metrics",
     "period": "$__interval",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Client Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 4 },
   "targets": [
    {
     "dimensions": { "Environment": "$env", "status": "PENDING" },
     "metricName": "queue_length",
     "namespace": "comms-publish-queue-stats-metrics",
     "period": "$__interval",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Request Enqueuing Rate (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 4 },
   "targets": [
    { "expression": "$A/60", "type": "math" }
   ]
  },
  {
   "title": "Client Name by ID",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expression": "filter description like /Quota available for client/\n | sort @timestamp asc\n | stats latest(clientName) as name by clientId",
     "logGroups": [
      { "arn": "$tllLogId", "name": "$tllLogId" }
     ],
     "queryMode": "Logs",
     "region": "eu-west-2",
     "statistic": "Average",
     "statsGroups": [ "clientId" ]
    }
   ]
  },
  {
   "title": "Total Client Requests Queued",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "Environment": "$env", "status": "PENDING" },
     "metricName": "virtual_queue_insertion",
     "namespace": "comms-process-queue-updates-lambda-metrics",
     "period": "$__interval",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 25 }, "options": { "content": "## Enrichment" } },
  {
   "title": "Enrichment Queue",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "dimensions": { "QueueName": "$enrichmentQueueName" },
     "label": "Queued",
     "metricName": "NumberOfMessagesSent",
     "namespace": "AWS/SQS",
     "period": "$__interval",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "QueueName": "$enrichmentQueueName" },
     "label": "Processed",
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "period": "$__interval",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "QueueName": "$enrichmentQueueName" },
     "label": "Backlog",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "period": "$__interval",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "QueueName": "$enrichmentDlqName" },
     "label": "DLQ",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "period": "$__interval",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Enrichment Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "QueueName": "$enrichmentQueueName" },
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "period": "$__interval",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/SQS", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "NumberOfMessagesDeleted", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$enrichmentQueueName" }, "property": { "name": "QueueName", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(NumberOfMessagesDeleted) FROM \"AWS/SQS\" WHERE QueueName = '$enrichmentQueueName'",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Enrichment Rate (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
   "targets": [
    { "expression": "$A/60", "type": "math" },
    { "expression": "$B/60", "type": "math" }
   ]
  },
  {
   "title": "Re-enrichment Queue",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "dimensions": { "QueueName": "$reEnrichmentQueueName" },
     "label": "Queued",
     "metricName": "NumberOfMessagesSent",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "QueueName": "$reEnrichmentQueueName" },
     "label": "Processed",
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "QueueName": "$reEnrichmentQueueName" },
     "label": "Backlog",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "QueueName": "$reEnrichmentDlqName" },
     "label": "DLQ",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Re-enrichment Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "QueueName": "$reEnrichmentQueueName" },
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "period": "$__interval",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/SQS", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "NumberOfMessagesDeleted", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$reEnrichmentQueueName" }, "property": { "name": "QueueName", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(NumberOfMessagesDeleted) FROM \"AWS/SQS\" WHERE QueueName = '$reEnrichmentQueueName'",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Enrichment PDS HTTP response status (campaign)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 34 },
   "targets": [
    {
     "dimensions": { "QueueName": "$reEnrichmentQueueName" },
     "metricName": "NumberOfMessagesSent",
     "metricQueryType": 1,
     "namespace": "comms-enrichment-metrics",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": {
       "name": "SCHEMA",
       "parameters": [
        { "name": "comms-enrichment-metrics", "type": "functionParameter" },
        { "name": "campaign_id", "type": "functionParameter" },
        { "name": "client_id", "type": "functionParameter" },
        { "name": "Environment", "type": "functionParameter" },
        { "name": "http_status_code", "type": "functionParameter" },
        { "name": "sending_group_id", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "groupBy": {
       "expressions": [
        { "property": { "name": "http_status_code", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "pds_message_sent", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(pds_message_sent) FROM SCHEMA(\"comms-enrichment-metrics\", campaign_id, client_id, Environment, http_status_code, sending_group_id) GROUP BY http_status_code",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Reenrichment PDS HTTP response status",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 34 },
   "targets": [
    {
     "dimensions": { "QueueName": "$reEnrichmentQueueName" },
     "metricName": "NumberOfMessagesSent",
     "metricQueryType": 1,
     "namespace": "comms-reenrichment-metrics",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": {
       "name": "SCHEMA",
       "parameters": [
        { "name": "comms-reenrichment-metrics", "type": "functionParameter" },
        { "name": "campaign_id", "type": "functionParameter" },
        { "name": "client_id", "type": "functionParameter" },
        { "name": "Environment", "type": "functionParameter" },
        { "name": "http_status_code", "type": "functionParameter" },
        { "name": "sending_group_id", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "groupBy": {
       "expressions": [
        { "property": { "name": "http_status_code", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "pds_message_sent", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(pds_message_sent) FROM SCHEMA(\"comms-reenrichment-metrics\", campaign_id, client_id, Environment, http_status_code, sending_group_id) GROUP BY http_status_code",
     "statistic": "Sum"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 41 }, "options": { "content": "## NHS App" } },
  {
   "title": "Dispatched",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-send-nhsapp-queue"
     },
     "label": "NHS App Requests Processed",
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/SQS", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "NumberOfMessagesDeleted", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "comms-$env-api-stl-send-nhsapp-queue"
         },
         "property": { "name": "QueueName", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(NumberOfMessagesDeleted) FROM \"AWS/SQS\" WHERE QueueName = 'comms-$env-api-stl-send-nhsapp-queue'",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Callbacks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-nhsapp-cb-queue.fifo"
     },
     "label": "NHS App Callbacks Processed",
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/SQS", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "NumberOfMessagesDeleted", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "comms-$env-api-stl-send-nhsapp-queue"
         },
         "property": { "name": "QueueName", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(NumberOfMessagesDeleted) FROM \"AWS/SQS\" WHERE QueueName = 'comms-$env-api-stl-send-nhsapp-queue'",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "NHS App Send Requests",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-send-nhsapp-queue"
     },
     "label": "Queued",
     "metricName": "NumberOfMessagesSent",
     "namespace": "AWS/SQS",
     "period": "$__interval",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": {
       "property": {
        "name": "comms-process-queue-updates-lambda-metrics",
        "type": "string"
       },
       "type": "property"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "virtual_queue_insertion", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$env" }, "property": { "name": "Environment", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(virtual_queue_insertion) FROM \"comms-process-queue-updates-lambda-metrics\" WHERE Environment = '$env'",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-send-nhsapp-queue"
     },
     "label": "Processed",
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "period": "$__interval",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "Environment": "$env" },
     "label": "Send Errors",
     "metricName": "comms-$env-api-srnl-sendrequests-nhsapp-error-count",
     "namespace": "comms-$env-lambda-errors",
     "period": "$__interval",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-send-nhsapp-queue"
     },
     "label": "Backlog",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "period": "$__interval",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-send-nhsapp-dlq"
     },
     "label": "DLQ",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "period": "$__interval",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "NHS App messages queued",
   "type": "status-history",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "Environment": "$env", "status": "PENDING" },
     "metricName": "virtual_queue_insertion",
     "namespace": "comms-process-queue-updates-lambda-metrics",
     "period": "$__interval",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": {
       "property": {
        "name": "comms-process-queue-updates-lambda-metrics",
        "type": "string"
       },
       "type": "property"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "virtual_queue_insertion", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$env" }, "property": { "name": "Environment", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(virtual_queue_insertion) FROM \"comms-process-queue-updates-lambda-metrics\" WHERE Environment = '$env'",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "NHS App Send Rate (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expression": "$A/60", "type": "math" }
   ]
  },
  {
   "title": "NHS App backlog (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "Environment": "$env", "status": "PENDING" },
     "metricName": "queue_length",
     "namespace": "comms-publish-queue-stats-metrics",
     "period": "$__interval",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": {
       "property": {
        "name": "comms-process-queue-updates-lambda-metrics",
        "type": "string"
       },
       "type": "property"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "virtual_queue_insertion", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$env" }, "property": { "name": "Environment", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(virtual_queue_insertion) FROM \"comms-process-queue-updates-lambda-metrics\" WHERE Environment = '$env'",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "NHS App callbacks processed",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-nhsapp-cb-queue.fifo"
     },
     "label": "Queued",
     "metricName": "NumberOfMessagesSent",
     "namespace": "AWS/SQS",
     "period": "$__interval",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": {
       "property": {
        "name": "comms-process-queue-updates-lambda-metrics",
        "type": "string"
       },
       "type": "property"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "virtual_queue_insertion", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$env" }, "property": { "name": "Environment", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(virtual_queue_insertion) FROM \"comms-process-queue-updates-lambda-metrics\" WHERE Environment = '$env'",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-nhsapp-cb-queue.fifo"
     },
     "label": "Processed",
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "period": "$__interval",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-nhsapp-cb-dlq"
     },
     "label": "DLQ",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "period": "$__interval",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-nhsapp-cb-queue.fifo"
     },
     "label": "Backlog",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "period": "$__interval",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "NHS App Expiry",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "label": "Poll Expired",
     "metricName": "PollRequestTtlItemsDeleted",
     "namespace": "comms-poll-request-ttl-metrics",
     "period": "$__interval",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": {
       "property": {
        "name": "comms-process-queue-updates-lambda-metrics",
        "type": "string"
       },
       "type": "property"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "virtual_queue_insertion", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$env" }, "property": { "name": "Environment", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(virtual_queue_insertion) FROM \"comms-process-queue-updates-lambda-metrics\" WHERE Environment = '$env'",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "TableName": "comms-$env-api-stg-comms-requests-with-ttl"
     },
     "label": "TTL Expired",
     "metricName": "TimeToLiveDeletedItemCount",
     "namespace": "AWS/DynamoDB",
     "period": "$__interval",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 78 }, "options": { "content": "## Gov.UK Notify" } },
  {
   "title": "Dispatched",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-send-govuknotify-queue"
     },
     "label": "GUN Messages Dispatched",
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/SQS", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "NumberOfMessagesDeleted", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "comms-$env-api-stl-send-nhsapp-queue"
         },
         "property": { "name": "QueueName", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(NumberOfMessagesDeleted) FROM \"AWS/SQS\" WHERE QueueName = 'comms-$env-api-stl-send-nhsapp-queue'",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Callbacks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-govuknotify-callback-queue"
     },
     "label": "GUN Callbacks Processed",
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/SQS", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "NumberOfMessagesDeleted", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "comms-$env-api-stl-send-nhsapp-queue"
         },
         "property": { "name": "QueueName", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(NumberOfMessagesDeleted) FROM \"AWS/SQS\" WHERE QueueName = 'comms-$env-api-stl-send-nhsapp-queue'",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Gov.UK Notify messages sent (inc letters)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-send-govuknotify-queue"
     },
     "label": "Queued",
     "metricName": "NumberOfMessagesSent",
     "namespace": "AWS/SQS",
     "period": "$__interval",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": {
       "property": {
        "name": "comms-process-queue-updates-lambda-metrics",
        "type": "string"
       },
       "type": "property"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "virtual_queue_insertion", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$env" }, "property": { "name": "Environment", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(virtual_queue_insertion) FROM \"comms-process-queue-updates-lambda-metrics\" WHERE Environment = '$env'",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-send-govuknotify-queue"
     },
     "label": "Processed",
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "period": "$__interval",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-send-govuknotify-dlq"
     },
     "label": "DLQ",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "period": "$__interval",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-send-govuknotify-queue"
     },
     "label": "Backlog",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "period": "$__interval",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "SMS + email messages queued",
   "type": "status-history",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "Environment": "$env", "status": "PENDING" },
     "metricName": "virtual_queue_insertion",
     "namespace": "comms-process-queue-updates-lambda-metrics",
     "period": "$__interval",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": {
       "property": {
        "name": "comms-process-queue-updates-lambda-metrics",
        "type": "string"
       },
       "type": "property"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "virtual_queue_insertion", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$env" }, "property": { "name": "Environment", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(virtual_queue_insertion) FROM \"comms-process-queue-updates-lambda-metrics\" WHERE Environment = '$env'",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "SMS + Email Send Rate (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expression": "$A/60", "type": "math" }
   ]
  },
  {
   "title": "SMS + Email backlog (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "Environment": "$env", "status": "PENDING" },
     "metricName": "queue_length",
     "namespace": "comms-publish-queue-stats-metrics",
     "period": "$__interval",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": {
       "property": {
        "name": "comms-process-queue-updates-lambda-metrics",
        "type": "string"
       },
       "type": "property"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "virtual_queue_insertion", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$env" }, "property": { "name": "Environment", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(virtual_queue_insertion) FROM \"comms-process-queue-updates-lambda-metrics\" WHERE Environment = '$env'",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Gov UK callbacks processed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-govuknotify-callback-queue"
     },
     "label": "Queued",
     "metricName": "NumberOfMessagesSent",
     "namespace": "AWS/SQS",
     "period": "$__interval",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": {
       "property": {
        "name": "comms-process-queue-updates-lambda-metrics",
        "type": "string"
       },
       "type": "property"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "virtual_queue_insertion", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$env" }, "property": { "name": "Environment", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(virtual_queue_insertion) FROM \"comms-process-queue-updates-lambda-metrics\" WHERE Environment = '$env'",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-govuknotify-callback-queue"
     },
     "label": "Processed",
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "period": "$__interval",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-govuknotify-callback-dlq"
     },
     "label": "DLQ",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "period": "$__interval",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-govuknotify-callback-queue"
     },
     "label": "Backlog",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "period": "$__interval",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 108 }, "options": { "content": "## Letters" } },
  {
   "title": "Letters requests queued",
   "type": "status-history",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "Environment": "$env", "status": "PENDING" },
     "metricName": "virtual_queue_insertion",
     "namespace": "comms-process-queue-updates-lambda-metrics",
     "period": "$__interval",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": {
       "property": {
        "name": "comms-process-queue-updates-lambda-metrics",
        "type": "string"
       },
       "type": "property"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "virtual_queue_insertion", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$env" }, "property": { "name": "Environment", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(virtual_queue_insertion) FROM \"comms-process-queue-updates-lambda-metrics\" WHERE Environment = '$env'",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Letters requests sent",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": {
      "QueueName": "comms-$env-api-lspl-csvbatch-queue"
     },
     "label": "MBA CSV Pipeline",
     "metricName": "NumberOfMessagesSent",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-csvbatchsynertec-queue"
     },
     "label": "Synertec CSV Pipeline",
     "metricName": "NumberOfMessagesSent",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-csvbatchprecisionproco-queue"
     },
     "label": "Precision Proco CSV Pipeline",
     "metricName": "NumberOfMessagesReceived",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "QueueName": "comms-$env-api-ecl-letterrenderer-queue"
     },
     "label": "Prerender",
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "SFTP Uploads",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "FunctionName": "comms-$env-api-ecl-sftpsend" },
     "label": "MBA SFTP Send",
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "FunctionName": "comms-$env-api-sftpsendlambda-sftpsendsynertec"
     },
     "label": "Synertec SFTP Send",
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "FunctionName": "comms-$env-api-sftpsendlambda-sftpsendprecisionproco"
     },
     "label": "Precision Proco SFTP Send",
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Letter backlog (letters only sent Sunday - Thursday)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "Environment": "$env", "queue_name": "*", "status": "PENDING" },
     "metricName": "queue_length",
     "namespace": "comms-publish-queue-stats-metrics",
     "period": "$__interval",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": {
       "property": {
        "name": "comms-process-queue-updates-lambda-metrics",
        "type": "string"
       },
       "type": "property"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "virtual_queue_insertion", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$env" }, "property": { "name": "Environment", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(virtual_queue_insertion) FROM \"comms-process-queue-updates-lambda-metrics\" WHERE Environment = '$env'",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Total Letters Sent",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": {
      "QueueName": "comms-$env-api-lspl-csvbatch-queue"
     },
     "label": "MBA CSV",
     "metricName": "NumberOfMessagesReceived",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-csvbatchsynertec-queue"
     },
     "label": "Synertec CSV",
     "metricName": "NumberOfMessagesReceived",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-csvbatchprecisionproco-queue"
     },
     "label": "Proco CSV",
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "QueueName": "comms-$env-api-ecl-letterrenderer-queue"
     },
     "label": "Prerender",
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Letter Count Per Supplier",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": {
      "QueueName": "comms-$env-api-lspl-csvbatch-queue"
     },
     "label": "MBA CSV",
     "metricName": "NumberOfMessagesReceived",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-csvbatchsynertec-queue"
     },
     "label": "Synertec CSV",
     "metricName": "NumberOfMessagesReceived",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-csvbatchprecisionproco-queue"
     },
     "label": "Proco CSV",
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "QueueName": "comms-$env-api-ecl-letterrenderer-queue"
     },
     "label": "Prerender",
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 130 }, "options": { "content": "## Router" } },
  {
   "title": "Post-router Throughput (Avg TPS - Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expression": "$A/60", "type": "math" },
    { "expression": "$B/60", "type": "math" },
    { "expression": "$C/60", "type": "math" },
    { "expression": "$D/60", "type": "math" },
    { "expression": "$E/60", "type": "math" },
    { "expression": "$K/60", "type": "math" }
   ]
  },
  {
   "title": "Routing Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": {
      "QueueName": "comms-$env-api-lspl-csvbatch-queue"
     },
     "label": "(MBA)",
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-csvbatchsynertec-queue"
     },
     "label": "(Synertec)",
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-reenrich-queue"
     },
     "label": "(Reenrichment)",
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-send-govuknotify-queue"
     },
     "label": "(GUN)",
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-send-nhsapp-queue"
     },
     "label": "(NHS App)",
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Router Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 135 },
   "targets": [
    {
     "dimensions": { "function_name": "comms-$env-api-rol-router" },
     "label": "CPU Time",
     "metricName": "cpu_total_time",
     "namespace": "LambdaInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "FunctionName": "comms-$env-api-rol-router" },
     "label": "Duration",
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "FunctionName": "comms-$env-api-rol-router" },
     "label": "Errors",
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  }
 ]
}